export const STORE_USER_MESSAGE = 'STORE_USER_MESSAGE';
export const ADD_BOT_MESSAGE = 'ADD_BOT_MESSAGE';
export const BOT_START_TYPING = 'BOT_START_TYPING';
export const BOT_STOP_TYPING = 'BOT_STOP_TYPING';
export const ADD_ERR_MESSAGE = 'ADD_ERR_MESSAGE';
export const END_MESSAGE_THREAD = 'END_MESSAGE_THREAD';
